name = str(input('Digite seu nome:'))
cpf = int(input('Digite seu CPF:'))
idade = int(input('Digite sua idade:'))
print('---------------------------')
print('Confirmação de Cadastro:')
print('Nome: ', name)
print('CPF: ', cpf)
print('Idade: ', idade)
print('---------------------------')